#
name: Create and publish image for valhalla-ui

on:
  push:
    branches:
      - main
jobs:
  build-and-push-image:
    name: Build image and push to dockerhub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      #
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: devdualtone/valhalla-ui
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
